### ISSUE TITLE
Do you expect replication / syncing to work?

### ISSUE THREAD

**Issue by zimpower** [stockulus/pouchdb-react-native#9]
Apologies if this is already asked / answered.
I tried the following in a React Native component.

```javascript
class pouchdb_test extends Component {
  constructor(props) {
    super(props)
    this.localDB = new PouchDB('mylocaldb', {adapter: 'asyncstorage'})
    this.remoteDB = new PouchDB('http://localhost:5984/myremotedb')
    this.localDB.sync(this.remoteDB)
}
```
And got the following error:
```javascript
runtime.js:1The regenerator/runtime module is deprecated; please import regenerator-runtime/runtime instead.

AppRegistry.js:82  Running application "pouchdb_test" with appParams: {"rootTag":1,"initialProps":{}}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF

ExceptionsManager.js: 61 
  Cannot read property 'length' of undefinedhandleException @ ExceptionsManager.js 61
  handleError @ InitializeJavaScriptAppEngine.js:89
  reportFatalError @ error-guard.js:30
  guard @ MessageQueue.js:44
  callFunctionReturnFlushedQueue @ MessageQueue.js: 87
  onmessage @ debuggerWorker.js:39

ExceptionsManager.js:76 
  Unhandled JS Exception: Cannot read property 'length' of undefinedreactConsoleError @ ExceptionsManager.js:76
  console.error @ YellowBox.js:48
  logIfNoNativeHook @ RCTLog.js:38
  __callFunction @ MessageQueue.js:184
  (anonymous function) @ MessageQueue.js:88
  guard @ MessageQueue.js:42
  callFunctionReturnFlushedQueue @ MessageQueue.js:87
  onmessage @ debuggerWorker.js:39
```
![screen shot 2016-05-05 at 21 29 51](https://cloud.githubusercontent.com/assets/3992242/15056291/af10bfe6-1308-11e6-893b-e0de6c3a4d7d.png)

**Comment by stockulus** [comment]
I expected it to work, but it does not :(
There is still a Problem with through2 in this situation

**Comment by stockulus** [comment]
Hi zimpower,

please try again with the newest version. It should work now.

Christoph

**Comment by zimpower** [comment]
Thanks Christoph,
Firstly - thanks for writing this library... big help!
The latest fix has definitely improved things - replication is working!
My test app syncs the local DB with a remote DB (LAN) and replicates state well.
Tested: 
1- starting with no network
2- starting with an empty local db
All looks good.

However, when I leave it running I still see a reoccurring warning, which I assume eventually leads to a crash after 8 warnings. See screenshots and code below. Am I doing something wrong?

<img width="1077" alt="screen shot 2016-05-08 at 10 33 16" src="https://cloud.githubusercontent.com/assets/3992242/15097069/5a40e48a-1508-11e6-8c87-c6d8f448fa0b.png">
After a few warnings: 
<img width="925" alt="screen shot 2016-05-08 at 10 38 25" src="https://cloud.githubusercontent.com/assets/3992242/15097091/0c9ef1da-1509-11e6-9e21-4b5290974cee.png">
Code:
```javascript
import PouchDB from 'pouchdb'
import 'pouchdb-asyncstorage-down'
// PouchDB.debug.enable('*')

import React, {
  AppRegistry,
  Component,
  StyleSheet,
  Text,
  View
} from 'react-native';

class pouchdb_test extends Component {

  constructor(props) {
    super(props)
    this.localDB = new PouchDB('mylocaldb', {adapter: 'asyncstorage'})
    this.remoteDB = new PouchDB('http://harare.local:5984/myremotedb')
    this.state = { docs: [] }
  }

  reload_state() {
    this.localDB.allDocs({
      include_docs: true,
    }).then( result => {
      docs = result.rows.map( row => {
        return {
          name: row.doc.name,
          type: row.doc.type,
          miles: row.doc.miles,
        }
      })
      this.setState({ docs: docs })
    }).catch( err => console.log("Error: ",err))
  }

  componentWillMount() {
    this.reload_state()
    this.localDB.sync(this.remoteDB, {
      live: true,
      retry: true
    }).on('change', pay_load => {
      console.log("yo, something changed!: ", pay_load.change.docs)
      this.reload_state()
    }).on('paused', info => {
      console.log("replication was paused, usually because of a lost connection:", info)
    }).on('active', info => {
      console.log("replication was resumed: ", info)
    }).on('error',  err => {
      console.log("totally unhandled error (shouldn't happen):", err)
    }).catch( err => console.log("Error: ",err))
  }

  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          Welcome to React Native!
        </Text>
        <Text style={styles.instructions}>
          To get started, edit index.ios.js
        </Text>
        <Text style={styles.instructions}>
          Press Cmd+R to reload,{'\n'}
          Cmd+D or shake for dev menu
        </Text>
        <Text style={styles.instructions}>
          {JSON.stringify(this.state.docs)}
        </Text>

      </View>
    );
  }
}

**Comment by stockulus** [comment]
Hi,

not sure what is going wrong there. I'll try to create an sample App this Week and try out. I'll let you know.

Christoph

**Comment by zimpower** [comment]
Thanks sir. 

Am I even using the right pattern for interacting with PouchDB?
My next step would be to try and integrate with redux...

**Comment by stockulus** [comment]
Hi,

still i did not find the time to implement a sample app, but the app i am currently developing the replication works now. (to a PouchDB with PouchDB-express) 

The internals of the PouchDB replication depend on atob, btoa and Blob. They are not available in core-js (react-native) so i added them. Properly you find the time and try it again.

Greetz from Cologne
Christoph

**Comment by felarof99** [comment]
Hi guys,
This library is a life saver, thanks!

@stockulus sync works for me. But I'm also getting the same warning messages like @zimpower (check attached images). I'm using your latest version (installed today)

"pouchdb": "^5.3.2",
"pouchdb-asyncstorage-down": "^1.1.6",

![warning](https://cloud.githubusercontent.com/assets/1309931/15240548/2341dd82-1908-11e6-8dea-3705e4052538.png)

![warning expanded](https://cloud.githubusercontent.com/assets/1309931/15240532/f3e51d42-1907-11e6-842f-98aefc513ba6.png)

**Comment by zimpower** [comment]
I upgraded to 1.1.0 but am still facing the issue. Bug seems to do with the `sync` with `options` including `{retry:true}` code, but I am not capable enough to help find it...

I'm getting around this for now by using a timer and polling on an interval... 
```javascript
  constructor(props) {
    super(props)
    this.localDB = new PouchDB('mylocaldb', {adapter: 'asyncstorage'})
    this.remoteDB = new PouchDB('http://localhost:5984/myremotedb')
    this.repeat_timer = setInterval( () =>  this.localDB.sync(this.remoteDB), 60000)
}

**Comment by felarof99** [comment]
I found another react-native-pouchdb implementation... https://github.com/carbureted/react-native-pouchdb

@zimpower have you checked it out?

**Comment by aprihodko** [comment]
When I try to sync documents with attachments I get the following

`[warn][tid:com.facebook.react.RCTNetworkingQueue][RCTNetworking.m:343] Received data was not a string, or was not a recognised encoding.`

Does anyone have the same issue?

**Comment by ichagas** [comment]
Convert to Base64, perhaps? Don't use Blob

[PouchDB Guide](https://pouchdb.com/guides/attachments.html#how-attachments-are-stored)

**Comment by aprihodko** [comment]
@ichagas I put them in PouchDB as Base64. And 'push' direction in syncing works fine - I see images in CouchDB. But then I try to pull changes, it fails with an error mentioned.

**Comment by stockulus** [comment]
@aprihodko would you mind to put an example in the "example" project and do a Pull Request?

**Comment by zimpower** [comment]
Any chance the db sync issue is related to this similar issue posted on pouch PB GitHub: [https://github.com/pouchdb/pouchdb/issues/5114](https://github.com/pouchdb/pouchdb/issues/5114).

I am syncing from simulator to couchdb on Mac on same LAN....

**Comment by stockulus** [comment]
I guess it is related. Currently PouchDB is being restructured. I am waiting this to finish. It will allow this Packages to restructure much easier. Properly it is necessary to reimplement the Pouchdb ajax functions for react native, but it will be possible then.

There is also a Bug with null and undefined values in abstract_level_down values, waiting for my Pull request to be integrated. So if you store null, you can get string 'null' back.

**Comment by stockulus** [comment]
PouchDb 5.4 has been Release:
I restructured the Project a bit, here is the new Bundle:
https://github.com/stockulus/pouchdb-asyncstorage-down/tree/master/packages/pouchdb-react-native
